---
- hosts: localhost
  tasks:
    - command: date
      register: date_val

    - debug: msg={{ date_val.stdout }}

    #- include: {{ ansible_host }}.yml
    #  when: test -f {{ ansible_host }}.yml
    - debug: msg="No configs found for this node, implementing default playbook"
